addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.7.0")
addSbtPlugin("com.47deg" % "sbt-microsites" % "0.7.6")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.0")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.2")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.11")
addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "0.3.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.4.0")
