addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.5.0")
addSbtPlugin("com.fortysevendeg"  % "sbt-microsites" % "0.4.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.0")
addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.4")
