addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.5.0")
addSbtPlugin("com.47deg"  % "sbt-microsites" % "0.5.3")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "1.1")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.4")
addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "0.1.14")
